
permissions:
  contents: write
name: Activity Commit

on:
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 11 * * *"
    - cron: "0 13 * * *"
    - cron: "0 15 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Daily Commit
        run: |
              git config user.name "GitHub Actions"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              echo "Atividade em $(date)" >> activity.log
              git add activity.log
              git diff-index --quiet HEAD || git commit -m "Commit automático: $(date)"
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
              git push origin HEAD:main
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
